/*
 * ksystemstats-ns-helper — mount-namespace helper for ksystemstats on ARM
 *
 * Creates a private mount namespace, bind-mounts the ARM-compatible cpuinfo
 * generated by ksystemstats-wrapper over /proc/cpuinfo, then execs
 * ksystemstats.  Requires CAP_SYS_ADMIN (set via setcap at install time).
 *
 * The UID never changes, so D-Bus session auth works normally.
 * Capabilities are dropped automatically when ksystemstats is exec'd (its
 * binary carries no file capabilities).
 *
 * Usage: ksystemstats-ns-helper <fake-cpuinfo-path>
 */

#define _GNU_SOURCE
#include <sched.h>
#include <sys/mount.h>
#include <unistd.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s <fake-cpuinfo-path>\n", argv[0]);
        return 1;
    }

    if (unshare(CLONE_NEWNS) != 0) {
        perror("unshare(CLONE_NEWNS)");
        return 1;
    }

    /* Prevent any mounts leaking back to the parent namespace */
    if (mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, NULL) != 0) {
        perror("mount --make-rprivate /");
        return 1;
    }

    if (mount(argv[1], "/proc/cpuinfo", NULL, MS_BIND, NULL) != 0) {
        perror("mount --bind /proc/cpuinfo");
        return 1;
    }

    execl("/usr/bin/ksystemstats", "/usr/bin/ksystemstats", NULL);
    perror("execl /usr/bin/ksystemstats");
    return 1;
}
