
obj-m += oneUpPower.o
#obj-m += test_power.o

# Build with:
#   make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
# Clean:
#   make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

