
obj-m += oneUpPower.o

#all:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
#
#clean:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

# Build with:
#   make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
# Clean:
#   make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

